# Test linear classifier
evaluate: True
data: cifar10/cifar10  
pretrained: saved/exp1/model_best.pth.tar  
batch_size: 64 
val_batch_size: 256
epochs: 1 
cos: True
sgd: True
lars: True
lr: 0.8 
wd: 0.0 
save_path: ../lincls_exp1/ 
resume: ../lincls_exp1/model_latest.pth.tar
num_classes: 10 #this should be defined for updating last layer output features of architecture
#wandb