# Configuration for testing the unsupervised classification
data: cifar10/cifar10 
hidden_dim: 4096 
dim: 128 
batch_size: 64 
cls_size: 10 
use_bn: True
num_hidden: 1 
activation: leaky_relu 
pretrained: saved/exp1/model_best.pth.tar
num_samples_per_class: 16 # should be a square number 1,4,9,16,...
save_path: ../saved/results/