# Training configuration file - 100 epochs - CIFAR10 
data: cifar10/cifar10
arch: resnet18
save_path: ./saved/cifar10/50epochs/
cls_size: 10
epochs: 50
batch_size: 16
subset: 5000
gpu: 0
use_bn: True
sgd: True
lars: True
activation: leaky_relu
cos: True
final_lr: 0.0048
lr: 4.8
queue_len: 50
wandb: subset-cifar10
dim: 128
num_hidden: 2
hidden_dim: 4096
 
#python test.py cifar10/cifar10 --hidden-dim 4096 --dim 128 --batch-size 16 --cls-size 10 --use-bn --num-hidden 1 --activation leaky-relu --pretrained saved/cifar10/50epochs/model_best.pth.tar --num-samples-per-class 16