# Training configuration file - 100 epochs - CIFAR10 
data: cifar10/cifar10
arch: resnet18
save_path: ./saved/exp1/
cls_size: 10
epochs: 100
batch_size: 64
subset: 0
gpu: 0
use_bn: True
sgd: True
lars: True
activation: leaky_relu
cos: True
final_lr: 0.0048
lr: 4.8
queue_len: 1000
wandb: cifar10
wandb_entity: andreacamilloni #Put your team name or your username
dim: 128
num_hidden: 2
hidden_dim: 4096
