# Training configuration file - 100 epochs - CIFAR10 
data: cifar10/cifar10
arch: resnet18
save-path: ./saved/cifar10/100epochs/
cls-size: 10
epochs: 100
batch_size: 8
subset: 1000
gpu: 0
use_bn: True
sgd: True
lars: True
activation: leaky-relu
cos: True
final_lr: 0.0048
lr: 4.8
queue_len: 100
wandb: group13
dim: 128
num_hidden: 1
hidden-dim: 4096
